### PR TITLE
Optimize ES queries

### PR DESCRIPTION
**Pull request by jmaupetit**
## Purpose

We've made some improvements to our ES index in production. By changing from default mapping to a custom definition of xAPI statement model keywords, we broke some ES requests.

## Proposal

- [x] drop support for legacy course ID filtering
- [x] optimize ES index mapping

### CODE REVIEW

**Review by quitterie-lcs — COMMENTED** [review]
We need to add `actor.account.name` and `verb.display.en-US`  to `keyword` mapping type

Also some context extensions for interacted event are used with keyword for dashboarding, and the display is broken in the dashboards

**Comment by jmaupetit** [comment]
> We need to add `actor.account.name` and `verb.display.en-US` to `keyword` mapping type

Maybe we'll handle this later, because:

1. I'm not sure at this time if we want to force this actor IFI,
2. we must be encouraged to query the `verb.id` and not the `verb.display.en-US` field right?

> Also some context extensions for interacted event are used with keyword for dashboarding, and the display is broken in the dashboards

Well spotted! I've fixed this.

**Comment by quitterie-lcs** [comment]
>     1. I'm not sure at this time if we want to force this actor IFI,
You're right! 
>     2. we must be encouraged to query the `verb.id` and not the `verb.display.en-US` field right?
Yes, for sure, the display is just for panel readability

**Review by quitterie-lcs — APPROVED** [review]

**Pull request merged**
